# The URL the site will be built for
base_url = "https://robyoung.digital"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
default_language = "en"

# Whether to generate an atom feed
generate_feed = false

taxonomies = [
  {name = "topics"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

extra_syntaxes_and_themes = ["syntaxes"]

[extra]
social = [
    {title = "twitter", url = "https://twitter.com/roryoung"},
    {title = "github", url = "https://github.com/robyoung"},
    {title = "linkedin", url = "https://www.linkedin.com/in/robyoung101"},
]
date_format = "%e %B %Y"


[link_checker]

skip_prefixes = [
  "https://dev.test",
  "https://www.digikey.com/en/maker/blogs/2020/understanding-stm32-naming-conventions",
]

skip_anchor_prefixes = [
  "https://www.openssl.org/docs/manmaster/man1/x509.html",
]
